
package br.inf.portalfiscal.nfe.wsdl.nfestatusservico;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NfeStatusServicoSoap", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NfeStatusServicoSoap {


    /**
     * 
     * @param nfeCabecMsg
     * @param nfeDadosMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico/nfeStatusServicoNF")
    @WebResult(name = "nfeStatusServicoNFResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico")
    @RequestWrapper(localName = "nfeStatusServicoNF", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", className = "br.inf.portalfiscal.nfe.wsdl.nfestatusservico.NfeStatusServicoNF")
    @ResponseWrapper(localName = "nfeStatusServicoNFResponse", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", className = "br.inf.portalfiscal.nfe.wsdl.nfestatusservico.NfeStatusServicoNFResponse")
    public String nfeStatusServicoNF(
        @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico")
        String nfeCabecMsg,
        @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico")
        String nfeDadosMsg);

}
